### ISSUE TITLE
Buildkite integration for Rust project

### ISSUE THREAD

**Issue by oguzkocer** [Automattic/wordpress-rs#12]
```[tasklist]
### Tasks
- [x] Build the project for all relevant architectures
- [x] Run unit tests
- [x] Generate docs (Don't publish until the project is open source: #16)
- [x] Run `clippy`
- [x] Run `rustfmt`
```
