### ISSUE TITLE
Buildkite integration for Swift project

### ISSUE THREAD

**Issue by oguzkocer** [Automattic/wordpress-rs#14]
```[tasklist]
### Tasks
- [x] Validate Swift package
- [x] Validate Podspec
- [x] Run Lint
- [x] Run unit & integration tests
- [x] Publish the Swift package
```

**Comment by jkmassel** [comment]
All of these items have been addressed.
